---
vagrantfile-local:
    vm:
        box: debian-wheezy72-x64-vbox43
        box_url: 'http://box.puphpet.com/debian-wheezy72-x64-vbox43.box'
        hostname: 'jake'
        network:
            private_network: 192.168.56.101
            forwarded_port:
                3QqRupZWS0je:
                    host: '8784'
                    guest: '22'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '4024'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            RJ9EliqhnwjH:
                id: vagrant-root
                source: /Users/jacob/Projects
                target: /vagrant-www
                nfs: 'true'
                bindfs:
                    target: /var/www
                    owner: 'www-data'
                    group: 'www-data'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - build-essential
        - vim
        - curl
        - git-core
        - bind9
        - redis-server
        - graphviz
        - subversion
        - php5-gmp
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
nginx:
    vhosts:
        GlRQe8kHiDsZ:
            server_name: cascade.dev
            www_root: /var/www/cascade/web
            listen_port: '80'
            index_files:
                - index.php
            envvars:
                - 'APP_ENV dev'
        Afjksfj3faSDFe:
            server_name: progress.dev
            www_root: /var/www/progress/web
            listen_port: '80'
            index_files:
                - index.php
            envvars:
                - 'APP_ENV dev'
php:
    version: '55'
    composer: '1'
    modules:
        php:
            - cli
            - curl
            - gd
            - intl
            - ldap
            - mcrypt
            - tidy
            - gmp
        pear: {  }
        pecl:
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
        error_log: /var/www/php_errors.log
    timezone: America/Los_Angeles
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_host: '192.168.56.1'
        xdebug.remote_port: '9001'
        xdebug.remote_autostart: '1'
        xdebug.profiler_enable: '0'
        xdebug.profiler_enable_trigger: '1'
        xdebug.profiler_output_dir: /var/tmp/profiles
xhprof:
    install: '1'
drush:
    install: 0
    settings:
        drush.tag_branch: 6.x
mysql:
    root_password: root
    bind_address: '127.0.0.1'
    phpmyadmin: 0
    adminer: 0
    databases: {  }
mongodb:
    install: 0
    auth: 1
    port: '27017'
    databases: {  }
beanstalkd:
    install: 0
    listenaddress: 0.0.0.0
    listenport: '13000'
    maxjobsize: '65535'
    maxconnections: '1024'
    binlogdir: /var/lib/beanstalkd/binlog
    binlogfsync: null
    binlogsize: '10485760'

