---
vagrantfile-local:
    vm:
        box: puphpet/centos65-x64
        box_url: puphpet/centos65-x64
        hostname: ''
        memory: '2024'
        cpus: '1'
        chosen_provider: virtualbox
        network:
            private_network: 192.168.56.101
            forwarded_port:
                0IHfegyDBuT2:
                    host: '5049'
                    guest: '22'
                Ir4hoK44C0zc:
                    host: '9001'
                    guest: '9001'
        post_up_message: ''
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
            vmware:
                numvcpus: 1
            parallels:
                cpus: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: site.pp
                module_path: puphpet/puppet/modules
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            Xod67o343nXB:
                owner: ''
                group: ''
                source: /Users/jmorrison/Projects
                target: /var/www
                sync_type: nfs
                rsync:
                    args:
                        - '--verbose'
                        - '--archive'
                        - '-z'
                    exclude:
                        - .vagrant/
                    auto: 'false'
        usable_port_range:
            start: 10200
            stop: 10500
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    install: '1'
    packages:
        - vim-common
        - htop
        - git
users_groups:
    install: '1'
    groups: {  }
    users: {  }
cron:
    install: '1'
    jobs: {  }
firewall:
    install: '1'
    rules:
        0qudKxWu3mOw:
            port:
                - '80'
                - '9000'
                - '9001'
                - '443'
            priority: '100'
            proto: tcp
            action: accept
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - rewrite
    vhosts:
        iktxbu4ixu1s:
            servername: progress.dev
            docroot: /var/www/progress/web
            port: '80'
            setenv:
                - 'APP_ENV dev'
            directories:
                8yxsbpivhihd:
                    provider: directory
                    path: /var/www/progress/web
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        mpc0s0kjzbsn:
            servername: cascade.dev
            docroot: /var/www/cascade/web
            port: '80'
            directories:
                yoirbfj4vh3w:
                    provider: directory
                    path: /var/www/cascade/web
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
        2clnnlutkcou:
            servername: webgrind.dev
            docroot: /var/www/webgrind
            port: '80'
            directories:
                kxa8r6xkrkvw:
                    provider: directory
                    path: ''
                    options:
                        - Indexes
                        - FollowSymlinks
                        - MultiViews
                    allow_override:
                        - All
                    require:
                        - all
                        - granted
                    custom_fragment: ''
            engine: php
            custom_fragment: ''
            ssl_cert: ''
            ssl_key: ''
            ssl_chain: ''
            ssl_certs_dir: ''
    mod_pagespeed: 0
nginx:
    install: '0'
    settings:
        default_vhost: 1
        proxy_buffer_size: 128k
        proxy_buffers: '4 256k'
    upstreams: {  }
    vhosts:
        xwvrp60j0e6j:
            proxy: ''
            server_name: cascade.dev
            www_root: /var/www/cascade/web
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            envvars:
                - 'APP_ENV dev'
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
        ijrslcet1pze:
            proxy: ''
            server_name: progress.dev
            www_root: /var/www/progress/web
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
        rjvx7b9gs6jl:
            proxy: ''
            server_name: webgrind.dev
            www_root: /var/www/webgrind
            listen_port: '80'
            location: \.php$
            index_files:
                - index.html
                - index.htm
                - index.php
            engine: php
            client_max_body_size: 1m
            ssl_cert: ''
            ssl_key: ''
php:
    install: '1'
    version: '56'
    composer: '1'
    composer_home: ''
    modules:
        php:
            - cli
            - gd
            - gmp
            - intl
            - ldap
            - mbstring
            - mcrypt
            - tidy
        pear: {  }
        pecl:
            - dbase
            - mongo
            - redis
            - pecl_http
    ini:
        display_errors: On
        error_reporting: '-1'
        session.save_path: /var/lib/php/session
    timezone: America/Los_Angeles
    mod_php: 0
hhvm:
    install: '0'
    nightly: 0
    composer: '1'
    composer_home: ''
    settings:
        host: 127.0.0.1
        port: '9000'
    ini:
        display_errors: On
        error_reporting: '-1'
    timezone: null
xdebug:
    install: '1'
    settings:
        xdebug.default_enable: '1'
        xdebug.cli_color: '1'
        xdebug.profiler_output_dir: /var/www/profiles
        xdebug.remote_autostart: '0'
        xdebug.remote_connect_back: '1'
        xdebug.remote_enable: '1'
        xdebug.remote_handler: dbgp
        xdebug.remote_port: '9000'
        xdebug.profiler_enable_trigger: '1'
        xdebug.remote_host: 192.168.56.1
xhprof:
    install: '0'
wpcli:
    install: '0'
    version: ''
drush:
    install: '0'
    version: 6.3.0
ruby:
    install: '1'
    versions:
        zZxiU5jESZjD:
            version: ''
nodejs:
    install: '1'
    npm_packages: {  }
python:
    install: '1'
    packages: {  }
    versions:
        8HqYauDE00rh:
            version: ''
mysql:
    install: '1'
    override_options: {  }
    root_password: root
    adminer: 0
    databases:
        QHoPbsWFIN5G:
            grant:
                - ALL
            name: cascade
            host: localhost
            user: cascade
            password: cascade
            sql_file: ''
        1llIK5chxjHo:
            grant:
                - ALL
            name: progress
            host: localhost
            user: progress
            password: progress
            sql_file: ''
        84fDkejJCOQj:
            grant:
                - ALL
            name: marina
            host: localhost
            user: marina
            password: marina
            sql_file: ''
postgresql:
    install: '0'
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: '0'
    override_options: {  }
    root_password: '123'
    adminer: 0
    databases: {  }
    version: '10.0'
sqlite:
    install: '0'
    adminer: 0
    databases:
        dA5ZpVBCODa2:
            name: ''
            owner: vagrant
            group: ''
            mode: '755'
            sql_file: ''
mongodb:
    install: '0'
    settings:
        auth: 1
        port: '27017'
    databases:
        n3JAjtO2Ah3p:
            name: progress
            user: progress
            password: progress
redis:
    install: '1'
    settings:
        conf_port: '6379'
mailcatcher:
    install: '0'
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/rvm/wrappers/default
        from_email_method: inline
beanstalkd:
    install: '0'
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: '0'
    settings:
        port: '5672'
elastic_search:
    install: '0'
    settings:
        version: ''
        java_install: true
solr:
    install: '0'
    settings:
        version: ''
        port: ''

